### ISSUE TITLE
Upgrading to version 0.9.8 causes breaking changes in projects using Node v6.x

### ISSUE THREAD

**Issue by srogers909** [rse/grunt-merge-json#20]
In projects using version 6 of Node, the latest version of **grunt-merge-json** causes breaking changes.  This is due to the 'Chalk' dependency of version 4.x which supports only Node v10+ (https://github.com/chalk/chalk/commit/61999a4e77f7d4ca0631f6c833b9ad5d76d925d5).  In our project, we had the package.json setting for **grunt-merge-json** to be ^0.9.5 which would allow non-breaking updates and had to revert to using 0.9.5 specifically _(without the carrot)_ to fix this issue.

We were expecting this module to conform to semantic versioning thus didn't expect a PATCH version update to cause a break in v6.2.0. In my opinion, your change **should** have been a major version update in order to not break projects still on old Node versions.

**Comment by rse** [comment]
Sorry that the recent change broke your situation and that I've not met your personal expectation of strict semantic versioning. But, to be honest, for any 0.9 version of my tons of software components I never use any strict semantics. At least not for any changes to dependencies which just affects a Node version which already went end-of-life 3(!) years ago.

**Comment by srogers909** [comment]
Very poor response to someone who uses your node module.  

My point is that there may be other projects, like mine, that would be expecting non-breaking changes through semantic versioning using your module.  You can't depend on everyone upgrading to the latest Node version while using your module.  As not everyone is so free to do so.  You're welcome to blow it off, but the reality is that all node modules should be using semantic versioning.  As per, https://docs.npmjs.com/about-semantic-versioning
